"""descreva aqui a mudança que voce fez

Revision ID: 093428d8e693
Revises: 
Create Date: 2025-02-07 13:58:09.659728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093428d8e693'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aulas', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
