"""Adiciona coluna tipo_servico à tabela servicos

Revision ID: fe215b341193
Revises: 
Create Date: 2024-12-11 21:24:51.472108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe215b341193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_servico', sa.String(length=50), nullable=False, server_default='fisioterapia'))
        batch_op.add_column(sa.Column('planos', sa.JSON(), nullable=True))
        batch_op.alter_column(
            'nome',
            existing_type=sa.String(length=255),  # Ajuste o tipo existente conforme seu banco de dados
            nullable=False                        # Atualize conforme necessário
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.alter_column(
            'nome',
            existing_type=sa.String(length=255),  # Tipo existente antes da alteração
            nullable=True                         # Estado anterior
        )
        batch_op.drop_column('planos')
        batch_op.drop_column('tipo_servico')
    # ### end Alembic commands ###
